### ISSUE TITLE
Geospatial shapes (polygons and lines)

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMaps#17]
What is requested here is support for geospatial shapes, such as polygons and lines, in Semantic Maps. This is a long-standing functionality request, recently raised again at SMWCon, and there have been attempts to make some progress, but a dedicated report for it has been wanting so far.  

I will leave it to others to consider whether (1) geospatial shapes should be recognised by a new SMW data type (compare the WikiData request below) or whether (2) entire strings should be stored as 'raw' property values of type "Text" (I guess there would be a preference for the former). 

Related posts:
A discussion from May 2012: http://wikimedia.7.x6.nabble.com/Semantic-mediawiki-and-map-data-td4976131.html#a4976171
June/July 2013: http://wikimedia.7.x6.nabble.com/Maps-and-Semantic-Maps-integrating-other-mapping-services-td5007885.html#a5009134
WikiData: https://phabricator.wikimedia.org/T57549

**Comment by PeterTheOne** [comment]
This seem related to #13 (or is it even a duplicate?)

**Comment by JeroenDeDauw** [comment]
This seems to be a supertype of the lines one.

**Comment by JeroenDeDauw** [comment]
I just found that there is code dealing with polygons in this extension. It was added in 2012 by @nischayn22. I totally forgot about this. Might not be documented at all, and also might have never worked, I don't know. The internal docs state they code has been there since the 2.1 release, though no such release is present in the README or git tag list. @kghbln any idea, of is this another chocolate? :)

This code adds a data value of type `_gpo`.

Relevant code:

* PolygonHandler
* SMGeoPolygonsValue
* Usage in SMQueryHandler

Currently this is very likely broken, as PolygonHandler references classes from Maps that got renamed in Maps 3.0.

**Comment by nischayn22** [comment]
It did work then but I can assume that its going to be broken now. It was part of a project I was doing which kind of stopped midway :/

Here's the demo I did for it in 2012 SMWCon https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/New_features_in_Maps_and_Semantic_Maps

I hope someone can rework on it and maybe find my code useful as a starting point.

**Comment by JeroenDeDauw** [comment]
Thanks for explaining!

**Comment by JeroenDeDauw** [comment]
Now tracked at https://github.com/JeroenDeDauw/Maps/issues/239
